# Generated by Django 5.2.4 on 2025-07-31 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('integration_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('integration_typ', models.CharField(choices=[('1', 'nothing')], max_length=20)),
                ('integration_details', models.JSONField(blank=True, null=True)),
                ('last_sync', models.DateField()),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
