version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"


# version: '3.8'

# services:
#   db:
#     image: postgres:15
#     ports:
#       - "5433:5432"
#     environment:
#       POSTGRES_USER: test1
#       POSTGRES_PASSWORD: test1
#       POSTGRES_DB: test1
#     volumes:
#       - pgdata:/var/lib/postgresql/data

#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/app
#     ports:
#       - "8001:8000"
#     depends_on:
#       - db
#     environment:
#       - DATABASE_URL=postgresql://test1:test1@db:5432/test1

# volumes:
#   pgdata:
