# Generated by Django 5.2.3 on 2025-07-14 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('activity_type', models.CharField(choices=[('shopping', 'SHOPPING')], max_length=20)),
                ('activity_details', models.JSONField()),
                ('image', models.JSONField()),
                ('location', models.TextField()),
                ('url', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('activity_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('integration_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('integration_type', models.CharField(choices=[('football', 'LIBRARY')], max_length=20)),
                ('integration_details', models.JSONField()),
                ('last_sync', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=225)),
                ('page_slug', models.CharField(max_length=225)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('last_login', models.DateTimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.activity')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.integration')),
            ],
        ),
    ]
