# Generated by Django 5.2.4 on 2025-07-31 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('1', 'Playing'), ('2', 'TV'), ('3', 'Shopping')], max_length=20)),
                ('activity_details', models.JSONField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='photo/%Y/%m/%d')),
                ('location', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('activity_date', models.DateTimeField()),
            ],
        ),
    ]
