# Generated by Django 5.2.4 on 2025-07-20 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('Playing', 'Playing'), ('TV', 'TV'), ('Shopping', 'Shopping')], max_length=20)),
                ('activity_details', models.JSONField()),
                ('image', models.ImageField(upload_to='photo/%Y/%m/%d')),
                ('location', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('create_at', models.DateField(default=datetime.date.today)),
                ('activity_date', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
    ]
