# Generated by Django 5.2.3 on 2025-07-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('activity_type', models.CharField(choices=[('shopping', 'SHOPPING')], max_length=20)),
                ('activity_details', models.JSONField()),
                ('image', models.JSONField()),
                ('location', models.TextField()),
                ('url', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('activity_date', models.DateTimeField()),
            ],
        ),
    ]
