# Generated by Django 5.2.4 on 2025-08-14 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityModels',
            fields=[
                ('activity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('1', 'Playing'), ('2', 'Shopping'), ('3', 'TV')], max_length=20)),
                ('activity_details', models.JSONField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='photo/%Y/%m/%d')),
                ('location', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('activity_date', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
