# Generated by Django 5.2.4 on 2025-07-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_activity_activity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
