# Generated by Django 5.2.4 on 2025-07-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='page_slug',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
